version: '3'

services: 
  backend:
    build:
      context: backend
    container_name: backend
    command: yarn dev
    volumes:
      - ./backend:/usr/src/app
    tty: true
    ports:
      - "3333:3333"
    networks:
      - postgres_ntwk

  frontend:
    build:
      context: frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  postgres:
    build:
      context: ./database
    container_name: postgres
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    networks:
      - postgres_ntwk

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./database/.env
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres_ntwk

networks:
  postgres_ntwk:
    driver: bridge