version: '3'

services: 
  backend:
    build: 
      context: backend
    container_name: backend
    command: yarn dev
    volumes:
      - ./backend:/usr/src/app
    tty: true
    ports:
      - "3333:3333"
  frontend:
    build: 
      context: frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
    tty: true
    ports:
      - "3000:3000"