version: '3'

services: 
  backend:
    build:
      context: backend
    container_name: backend
    command: yarn dev
    volumes:
      - ./backend:/usr/src/app
    tty: true
    ports:
      - "3333:3333"
    networks:
      - pet_adopt_network
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    networks:
      - pet_adopt_network

  postgres:
    build:
      context: ./database
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pet_adopt_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./database/.env
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - pet_adopt_network

networks:
  pet_adopt_network:
    name: pet_adopt_network
    driver: bridge

volumes:
  postgres_data:
